name: Feature Branch
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    name: Unit-Test
    runs-on: ubuntu-18.04
 steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14-ea
      - name: Maven Package
        run: mvn clean package
      - name: Maven Verify
        run: mvn clean verify -DskipTests